/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-10-25 04:49:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.activity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.hibernate.internal.build.AllowSysOut;
import java.util.List;
import activity.model.ActivityBean;

public final class manageActivityPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/websiteForm/enterpriseWebsiteBody1.jsp", Long.valueOf(1628060228972L));
    _jspx_dependants.put("/websiteForm/enterpriseWebsiteBody2.jsp", Long.valueOf(1627867491167L));
    _jspx_dependants.put("/websiteForm/enterpriseWebsiteHead.jsp", Long.valueOf(1627867491193L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("activity.model.ActivityBean");
    _jspx_imports_classes.add("org.hibernate.internal.build.AllowSysOut");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>manageActivityPage</title>\r\n");
      out.write("<style>\r\n");
      out.write("	*{\r\n");
      out.write("		padding: 0;\r\n");
      out.write("		margin: 0;\r\n");
      out.write("		list-style: none;\r\n");
      out.write("	}\r\n");
      out.write("	body{\r\n");
      out.write("		background-color: lightgreen;\r\n");
      out.write("	}\r\n");
      out.write("	.container{\r\n");
      out.write("		width:1200px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		background-color: lightgreen;\r\n");
      out.write("	}\r\n");
      out.write("	.container>h3{\r\n");
      out.write("		padding: 20px 0;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		font-size: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	.container .activityArea{\r\n");
      out.write("		width: 1096px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction:row;\r\n");
      out.write("		flex-wrap:wrap;\r\n");
      out.write("		justify-content: flex-start;\r\n");
      out.write("		align-content: flex-start;\r\n");
      out.write("		/* align-items: center; */\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.container .activityBox{\r\n");
      out.write("		width: 480px;\r\n");
      out.write("		height:250px;\r\n");
      out.write("		margin: 20px;\r\n");
      out.write("		/* flex-grow: 1; */\r\n");
      out.write("		/* flex-basis: ; */\r\n");
      out.write("		/* flex-shrink: ; */\r\n");
      out.write("		/* align-items: ; */\r\n");
      out.write("		border: 4px solid rgba(0,0,0,0);\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		background-color: lightgoldenrodyellow;\r\n");
      out.write("		transition: border .5s;\r\n");
      out.write("	}\r\n");
      out.write("	.container .activityBox a{\r\n");
      out.write("		display: block;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		text-decoration:none;\r\n");
      out.write("		color: #000;\r\n");
      out.write("	}\r\n");
      out.write("	.container .activityBox h2{\r\n");
      out.write("		font-size: 27px;\r\n");
      out.write("	}\r\n");
      out.write("	.container .activityBox h4{\r\n");
      out.write("		padding: 80px 0 ;\r\n");
      out.write("		font-size: 30px;\r\n");
      out.write("		line-height:30px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("	}\r\n");
      out.write("	.container .activityBox:last-child{\r\n");
      out.write("		justify-content: flex-start;\r\n");
      out.write("		border: 4px dashed rgba(0,0,0,0);\r\n");
      out.write("	}\r\n");
      out.write("	.container .activityBox:last-child a{\r\n");
      out.write("		display: block;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		text-decoration:none;\r\n");
      out.write("	}\r\n");
      out.write("	.container .activityBox:last-child .addImg{\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		width: 140px;\r\n");
      out.write("		margin-top: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	.container .activityBox:last-child h3{\r\n");
      out.write("		font-size: 30px;\r\n");
      out.write("		color:rgb(102, 211, 102)\r\n");
      out.write("	}\r\n");
      out.write("	.container .activityBox:hover{\r\n");
      out.write("		cursor:pointer;\r\n");
      out.write("		border: 4px solid rgba(0,0,0,1);\r\n");
      out.write("	}\r\n");
      out.write("	.container .activityBox:last-child:hover{\r\n");
      out.write("		cursor:pointer;\r\n");
      out.write("		border: 4px dashed rgba(0,0,0,1);\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/websiteForm/homePageTemplateCss/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/websiteForm/homePageTemplateCss/myStyle.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	// 編碼設訂
	response.setContentType("text/html;charset=UTF-8");
	request.setCharacterEncoding("UTF-8");

      out.write('	');
      out.write('\r');
      out.write('\n');

	// 取得帳號資料
	String UserID = (String)session.getAttribute("UserID");
	String ClassMember = (String)session.getAttribute("ClassMember");
	String Vat = (String)session.getAttribute("Vat");
	String Longin = (String)session.getAttribute("Longin");
	// Longin != null 為已登入狀態
	// Longin == null 為未登入狀態
	
	
	// 未登入、已登入側邊欄各項目連結不一樣
	String enterpriseDataLink =null;
	String storeManageLink =null;

	String orderQueryLink =null;
	String commentLink =null;
	String activityLink =null;
	
	if(Longin == null){ // 未登入狀態
		
		enterpriseDataLink = "'#'";
		storeManageLink = "'#'";
		activityLink ="'#'";
		
	}else{ // 已登入狀態
		
		enterpriseDataLink = "'" + request.getContextPath()  +"\\member\\ModifyFirstMemberVendor.jsp'";
		storeManageLink = "'"+ request.getContextPath() + "/checkLoginEntry.controller'"; 
		activityLink = "'"+ request.getContextPath() + "/toActivityManagePage.controller'";
	}
	
	
	
	//System.out.println("UserID="+UserID);
	//System.out.println("ClassMember="+ClassMember);
	//System.out.println("Vat="+Vat);
	System.out.println("Longin="+Longin);


      out.write("	\r\n");
      out.write("        <nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-dark\">\r\n");
      out.write("            <!-- Navbar Brand-->\r\n");
      out.write("            <a class=\"navbar-brand ps-3 myFontTC myLetterSpace2\" href=\"#\">飲料線上訂</a>\r\n");
      out.write("            <!-- Sidebar Toggle-->\r\n");
      out.write("            <button class=\"myNavBtnDisappear btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0\" id=\"sidebarToggle\" href=\"#!\"><i class=\"fas fa-bars\"></i></button>\r\n");
      out.write("            <!-- Navbar Search-->\r\n");
      out.write("            <form class=\"d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <!-- \r\n");
      out.write("                        搜尋欄\r\n");
      out.write("                        <input class=\"form-control\" type=\"text\" placeholder=\"Search for...\" aria-label=\"Search for...\" aria-describedby=\"btnNavbarSearch\" />\r\n");
      out.write("                        <button class=\"btn btn-primary\" id=\"btnNavbarSearch\" type=\"button\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                     -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("    ");

	// 登錄成功狀態
	if (Longin != null) {
	
      out.write("\r\n");
      out.write("	<div class=\"myFontTC myFontColorWhite myLetterSpace2 \">\r\n");
      out.write("		");
      out.print(UserID);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\r\n");
      out.write("		<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("			id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("			aria-expanded=\"false\"><i class=\"fas fa-user fa-fw\"></i></a>\r\n");
      out.write("			<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("				aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("				<!-- LinkTag-登出 -->\r\n");
      out.write("				<li><a class=\"dropdown-item myFontTC myTextCenter\"\r\n");
      out.write("					href=\"");
      out.print(request.getContextPath() );
      out.write("/login/LoginPage.jsp\">登出</a></li>\r\n");
      out.write("			</ul></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");

	// 未登錄狀態
	if (Longin == null) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- LinkTag-登入 -->\r\n");
      out.write("	<a href=\"LoginPage.jsp\" class=\"myLoginBtn\">登入</a>\r\n");
      out.write("	<!-- LinkTag-註冊 -->\r\n");
      out.write("	<a href=\"NewMemberAll.jsp\" class=\"mySignUpBtn\">註冊</a>\r\n");
      out.write("\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div id=\"layoutSidenav\">\r\n");
      out.write("            <div id=\"layoutSidenav_nav\">\r\n");
      out.write("                <nav class=\"sb-sidenav accordion sb-sidenav-dark\" id=\"sidenavAccordion\">\r\n");
      out.write("                    <div class=\"sb-sidenav-menu\">\r\n");
      out.write("                        <div class=\"nav\">\r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading myLetterSpace2\">企業</div>\r\n");
      out.write("                            <!-- LinkTag-企業資訊 -->\r\n");
      out.write("                            <a class=\"nav-link myFontTC myLetterSpace2\" href=");
      out.print(enterpriseDataLink);
      out.write(" >\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-tachometer-alt\"></i></div>\r\n");
      out.write("                                企業資訊\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading myLetterSpace2\">店家</div>\r\n");
      out.write("                            <!--  -->\r\n");
      out.write("                            <a class=\"nav-link collapsed myFontTC myLetterSpace2\" href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\" aria-controls=\"collapseLayouts\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-columns\"></i></div>\r\n");
      out.write("                                管理\r\n");
      out.write("                                <div class=\"sb-sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"collapse\" id=\"collapseLayouts\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("                                <nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=");
      out.print(storeManageLink);
      out.write(" >店家管理</a>\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=\"#\">新增店家</a>\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=\"#\">查詢店家</a>\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=\"#\">修改店家</a>\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=\"#\">刪除店家</a>\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=");
      out.print(activityLink);
      out.write(" >店家活動</a><!-- 2021/8/4 臨時加 -->\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!--  -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"layoutSidenav_content\">\r\n");
      out.write("                <main>\r\n");
      out.write("                    <div class=\"container-fluid px-4\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');
 int activityIndex = 1; 
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h3>目前活動</h3>\r\n");
      out.write("		<ul class=\"activityArea\">\r\n");
      out.write("		\r\n");
      out.write("			");

			List<ActivityBean> allActivity = (List<ActivityBean>)request.getAttribute("allActivity");
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			");

			for(ActivityBean item : allActivity) {  
				
				// String activityDetailString = "\"./activityDetailServlet?ID="+ item.getID() +"\"";
				String activityDetailString = "/toUpdateActivityPage.controller?ID="+ item.getID() ;
			
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("			<li class=\"activityBox\">\r\n");
      out.write("				<a href=\"");
      out.print( request.getContextPath() + activityDetailString );
      out.write("\">\r\n");
      out.write("					<h2>活動");
      out.print( activityIndex );
      out.write(":</h2>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					 \r\n");
      out.write("					<h4>");
      out.print(item.getActivityTopic() );
      out.write("</h4>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					 \r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			");

				activityIndex++;
			}
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<li class=\"activityBox\">\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath());
      out.write("/toAddNewActivity.controller\">\r\n");
      out.write("					<img src=\"");
      out.print(request.getContextPath());
      out.write("/activity/images/add.png\" class=\"addImg\" alt=\"addImg\">\r\n");
      out.write("					<h3>增加活動</h3>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write(" 			</div>\r\n");
      out.write("        </main>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/websiteForm/homePageTemplateJS/js/scripts.js\"></script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
