/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-10-25 04:50:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.activity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import activity.model.ActivityBean;

public final class updateActivity_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("activity.model.ActivityBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>setActivity</title>\r\n");
      out.write("	<!-- jQuery CSS 樣式(配合 jQuery UI)-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/Library/jquery-ui-1.12.1/jquery-ui.css\">\r\n");
      out.write("	<style>\r\n");
      out.write("		*{  \r\n");
      out.write("			padding: 0;\r\n");
      out.write("			margin: 0;\r\n");
      out.write("		}\r\n");
      out.write("		body{\r\n");
      out.write("			background-color:rgb(248, 255, 180);\r\n");
      out.write("		}\r\n");
      out.write("		.container{\r\n");
      out.write("			width:1300px;\r\n");
      out.write("			margin: 80px auto 200px;\r\n");
      out.write("			background-color:lightskyblue;\r\n");
      out.write("			border-radius: 30px;\r\n");
      out.write("			box-shadow: 8px 8px 10px rgba(100,100,100,.5);\r\n");
      out.write("		}\r\n");
      out.write("		.container .header{\r\n");
      out.write("			height:40px;\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			padding: 30px 0;\r\n");
      out.write("			background-color:rgb(241, 148, 42);\r\n");
      out.write("			border-radius: 30px 30px 0 0;\r\n");
      out.write("			font-size:40px;\r\n");
      out.write("			line-height: 40px;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			letter-spacing:3px; /* 字距*/\r\n");
      out.write("		}\r\n");
      out.write("		.container form{\r\n");
      out.write("			display: block;\r\n");
      out.write("			padding: 20px 0 50px;\r\n");
      out.write("		}\r\n");
      out.write("		.container .inputItem{\r\n");
      out.write("			font-size: 23px;\r\n");
      out.write("			line-height: 30px;\r\n");
      out.write("			padding: 25px 0 0 30px;\r\n");
      out.write("		}\r\n");
      out.write("		.container .inputItem label{\r\n");
      out.write("			display: inline-block;\r\n");
      out.write("			height: 25px;\r\n");
      out.write("			width:  8%;\r\n");
      out.write("			margin-left: 8%;\r\n");
      out.write("			margin-right: 1%;\r\n");
      out.write("		}\r\n");
      out.write("		.container input,textarea,select{\r\n");
      out.write("			border:none;\r\n");
      out.write("		}\r\n");
      out.write("		.container input:focus,\r\n");
      out.write("		.container textarea:focus,\r\n");
      out.write("		.container select:focus{	/* 取消選擇時輸入格的外框變化 */\r\n");
      out.write("			outline: none;\r\n");
      out.write("			background-color:rgb(242, 250, 173);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.container .inputBox,\r\n");
      out.write("		.container .selectBox{\r\n");
      out.write("			position: relative;\r\n");
      out.write("			top:-4px;	/* 輸入格微調	*/\r\n");
      out.write("			height:36px;\r\n");
      out.write("			padding-left: 5px;\r\n");
      out.write("			vertical-align: top;\r\n");
      out.write("			background-color:rgb(247, 250, 219);\r\n");
      out.write("			font-size: 23px;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.container .activityTopic{\r\n");
      out.write("			width:70%;\r\n");
      out.write("		}\r\n");
      out.write("		 .container .activityTimeYMD{\r\n");
      out.write("			width:150px;\r\n");
      out.write("		} \r\n");
      out.write("		.container .selectBox{\r\n");
      out.write("			font-size: 20px;\r\n");
      out.write("			margin-right: 10px;\r\n");
      out.write("			opacity: 1;\r\n");
      out.write("		}\r\n");
      out.write("		.container textarea{\r\n");
      out.write("			vertical-align: top;\r\n");
      out.write("			height:200px;\r\n");
      out.write("			width:70%;\r\n");
      out.write("			resize:none; /* 不能調整尺寸 */\r\n");
      out.write("			padding: 5px 0 5px 5px;\r\n");
      out.write("			background-color:rgb(247, 250, 219);\r\n");
      out.write("			font-size: 23px;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("		} \r\n");
      out.write("		.container .inputItem .activityTypeClass{\r\n");
      out.write("			height:15px;\r\n");
      out.write("			width: 15px;\r\n");
      out.write("			margin: 0 4px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.container .sendOutBtn{\r\n");
      out.write("			margin-left:225px;\r\n");
      out.write("			height:70px;\r\n");
      out.write("			padding: 0 30px;\r\n");
      out.write("			font-size: 23px;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("			box-shadow: 2px 2px 2px rgba(100,100,100,.5);\r\n");
      out.write("			border-radius: 3px;\r\n");
      out.write("			border: none;\r\n");
      out.write("		}\r\n");
      out.write("		.container .updateBtn{\r\n");
      out.write("			background-color: rgb(255, 190, 68);\r\n");
      out.write("		}\r\n");
      out.write("		.container .sendOutBtn:hover{\r\n");
      out.write("			background-color: rgb(255, 206, 115);\r\n");
      out.write("			color:rgb(59, 59, 59);\r\n");
      out.write("		}\r\n");
      out.write("		.container .deleteBtn{\r\n");
      out.write("			background-color: rgb(255, 54, 54);\r\n");
      out.write("		}\r\n");
      out.write("		.container .deleteBtn:hover{\r\n");
      out.write("			background-color: rgb(255, 124, 124);\r\n");
      out.write("			color:rgb(59, 59, 59);\r\n");
      out.write("		}\r\n");
      out.write("		.container .cancelBtn{\r\n");
      out.write("			background-color: rgb(255, 232, 188);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/* JS 會改到的部分 */\r\n");
      out.write("\r\n");
      out.write("		.container .inputBox.unchangeable,\r\n");
      out.write("		.container .selectBox.unchangeable,\r\n");
      out.write("		.container textarea.unchangeable\r\n");
      out.write("		{\r\n");
      out.write("			background-color: rgb(190, 190, 190);\r\n");
      out.write("		}\r\n");
      out.write("		.container .cancelBtn.unchangeable{\r\n");
      out.write("			display: none;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		ActivityBean oneActivity = (ActivityBean)request.getAttribute("oneActivity");
		
		// 開始時間:
		String startTimeString = oneActivity.getStartTime();
		String[] aa = startTimeString.split("-");
		int startTimeYYYY = Integer.parseInt(aa[0]); //年
		int startTimeMM = Integer.parseInt(aa[1]);   //月
		String[] bb = aa[2].split(" ");
		int startTimeDD = Integer.parseInt(bb[0]);  //日
		String[] cc = bb[1].split(":");
		int startTimeHH = Integer.parseInt(cc[0]);  //時
		
		// 結束時間:
		String endTimeString = oneActivity.getEndTime();
		String[] dd = endTimeString.split("-");
		int endTimeYYYY = Integer.parseInt(dd[0]); //年
		int endTimeMM = Integer.parseInt(dd[1]);   //月
		String[] ee = dd[2].split(" ");
		int endTimeDD = Integer.parseInt(ee[0]);  //日
		String[] ff = ee[1].split(":");
		int endTimeHH = Integer.parseInt(ff[0]);  //時
	
		// activityType 邏輯
		int activityTypeString = oneActivity.getActivityType();
		
		String activityType_1 = "";
		String activityType_2 = "";
		if( activityTypeString == 1){
			activityType_1 = "checked";
		}else if( activityTypeString == 2 ){
			activityType_2 = "checked";
		}
		
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"header\">\r\n");
      out.write("			活動設定\r\n");
      out.write("		</div>\r\n");
      out.write("		<form action=\"");
      out.print(request.getContextPath());
      out.write("/updateOneActivity.controller\" method=\"post\" id=\"form\">\r\n");
      out.write("			<div class=\"inputItem\">\r\n");
      out.write("				<label for=\"activityTopicId\">活動標題:</label>\r\n");
      out.write("				<input type=\"text\" class=\"inputBox activityTopic unchangeable\" name=\"activityTopic\" id=\"activityTopicId\" placeholder=\"輸入主題\" disabled value=\"");
      out.print( oneActivity.getActivityTopic() );
      out.write("\" >\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"inputItem\">\r\n");
      out.write("				<label for=\"\">活動時間:</label>\r\n");
      out.write("				<input type=\"text\" name=\"startTimeYMD\" id=\"startTimeYMD\" class=\"inputBox activityTimeYMD unchangeable\" placeholder=\"選擇日期\" disabled>\r\n");
      out.write("				<select name=\"startTimeH\" id=\"startTimeH\" class=\"selectBox unchangeable\" disabled>\r\n");
      out.write("					<option value=\"00\">00</option>\r\n");
      out.write("					<option value=\"01\">01</option>\r\n");
      out.write("					<option value=\"02\">02</option>\r\n");
      out.write("					<option value=\"03\">03</option>\r\n");
      out.write("					<option value=\"04\">04</option>\r\n");
      out.write("					<option value=\"05\">05</option>\r\n");
      out.write("					<option value=\"06\">06</option>\r\n");
      out.write("					<option value=\"07\">07</option>\r\n");
      out.write("					<option value=\"08\">08</option>\r\n");
      out.write("					<option value=\"09\">09</option>\r\n");
      out.write("					<option value=\"10\">10</option>\r\n");
      out.write("					<option value=\"11\">11</option>\r\n");
      out.write("					<option value=\"12\">12</option>\r\n");
      out.write("					<option value=\"13\">13</option>\r\n");
      out.write("					<option value=\"14\">14</option>\r\n");
      out.write("					<option value=\"15\">15</option>\r\n");
      out.write("					<option value=\"16\">16</option>\r\n");
      out.write("					<option value=\"17\">17</option>\r\n");
      out.write("					<option value=\"18\">18</option>\r\n");
      out.write("					<option value=\"19\">19</option>\r\n");
      out.write("					<option value=\"20\">20</option>\r\n");
      out.write("					<option value=\"21\">21</option>\r\n");
      out.write("					<option value=\"22\">22</option>\r\n");
      out.write("					<option value=\"23\">23</option>\r\n");
      out.write("				</select>時\r\n");
      out.write("				到\r\n");
      out.write("				<input type=\"text\" name=\"endTimeYMD\" id=\"endTimeYMD\" class=\"inputBox activityTimeYMD unchangeable\" placeholder=\"選擇日期\" disabled>\r\n");
      out.write("				<select name=\"endTimeH\" id=\"endTimeH\" class=\"selectBox unchangeable\" disabled>\r\n");
      out.write("					<option value=\"00\">00</option>\r\n");
      out.write("					<option value=\"01\">01</option>\r\n");
      out.write("					<option value=\"02\">02</option>\r\n");
      out.write("					<option value=\"03\">03</option>\r\n");
      out.write("					<option value=\"04\">04</option>\r\n");
      out.write("					<option value=\"05\">05</option>\r\n");
      out.write("					<option value=\"06\">06</option>\r\n");
      out.write("					<option value=\"07\">07</option>\r\n");
      out.write("					<option value=\"08\">08</option>\r\n");
      out.write("					<option value=\"09\">09</option>\r\n");
      out.write("					<option value=\"10\">10</option>\r\n");
      out.write("					<option value=\"11\">11</option>\r\n");
      out.write("					<option value=\"12\">12</option>\r\n");
      out.write("					<option value=\"13\">13</option>\r\n");
      out.write("					<option value=\"14\">14</option>\r\n");
      out.write("					<option value=\"15\">15</option>\r\n");
      out.write("					<option value=\"16\">16</option>\r\n");
      out.write("					<option value=\"17\">17</option>\r\n");
      out.write("					<option value=\"18\">18</option>\r\n");
      out.write("					<option value=\"19\">19</option>\r\n");
      out.write("					<option value=\"20\">20</option>\r\n");
      out.write("					<option value=\"21\">21</option>\r\n");
      out.write("					<option value=\"22\">22</option>\r\n");
      out.write("					<option value=\"23\">23</option>\r\n");
      out.write("				</select>時\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"inputItem\">\r\n");
      out.write("				<label for=\"activityContentId\">活動內容:</label>\r\n");
      out.write("				<textarea name=\"activityContent\" class=\"unchangeable\" id=\"activityContentId\" placeholder=\"請輸入內容\" disabled>");
      out.print( oneActivity.getActivityContent()  );
      out.write("</textarea>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"inputItem\">\r\n");
      out.write("				<label for=\"activityTopicId\">活動圖片:</label>\r\n");
      out.write("				<input type=\"text\" class=\"inputBox activityTopic\" style=\"background-color:rgb(173, 173, 173)\" name=\"activityTopic\" id=\"activityTopicId\" placeholder=\"未開放\" disabled=\"disabled\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"inputItem\">\r\n");
      out.write("				<label for=\"\">活動類型:</label>\r\n");
      out.write("				<input type=\"radio\" class=\"activityTypeClass unchangeable\" id=\"activityType1ID\" name=\"activityType\" value=\"1\" ");
      out.print(activityType_1 );
      out.write(" disabled >限時優惠\r\n");
      out.write("				<input type=\"radio\" class=\"activityTypeClass unchangeable\" id=\"activityType2ID\" name=\"activityType\" value=\"2\" ");
      out.print(activityType_2 );
      out.write(" disabled >優惠券\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 放 delete、ID 參數 -->\r\n");
      out.write("			<input type=\"hidden\" id=\"deleteValue\" name=\"deleteValue\" value=\"0\">\r\n");
      out.write("			<input type=\"hidden\" id=\"IDValue\" name=\"IDValue\" value=\"");
      out.print( oneActivity.getID() );
      out.write("\"  >\r\n");
      out.write("			<div class=\"inputItem\">\r\n");
      out.write("				<button  type=\"button\" class=\"sendOutBtn updateBtn\" id=\"updateBtn\" >修改活動</button>\r\n");
      out.write("				<button  type=\"button\" class=\"sendOutBtn deleteBtn\" id=\"deleteBtn\" >刪除活動</button>\r\n");
      out.write("				<input type=\"reset\" class=\"sendOutBtn cancelBtn unchangeable\" id=\"cancelBtn\" value=\"放棄修改\"> \r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- jQuery CDN -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.js\" integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<!-- jQuery UI -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/Library/jquery-ui-1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function(){\r\n");
      out.write("\r\n");
      out.write("			// 日期 UI\r\n");
      out.write("			$( \"#startTimeYMD\" ).datepicker();\r\n");
      out.write("			$( \"#endTimeYMD\" ).datepicker();\r\n");
      out.write("			\r\n");
      out.write("			function initDatepickerValue(){\r\n");
      out.write("				$( \"#startTimeYMD\" ).datepicker('setDate', new Date(");
      out.print( startTimeYYYY );
      out.write(',');
      out.write(' ');
      out.print( startTimeMM-1 );
      out.write(',');
      out.write(' ');
      out.print( startTimeDD );
      out.write("));\r\n");
      out.write("				$( \"#endTimeYMD\" ).datepicker('setDate', new Date(");
      out.print( endTimeYYYY );
      out.write(',');
      out.write(' ');
      out.print( endTimeMM-1 );
      out.write(',');
      out.write(' ');
      out.print( endTimeDD );
      out.write("));\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			initDatepickerValue();\r\n");
      out.write("			$('#startTimeH').find('option:eq('+");
      out.print( startTimeHH );
      out.write("+')').attr('selected',true);\r\n");
      out.write("			$('#endTimeH').find('option:eq('+");
      out.print( endTimeHH );
      out.write("+')').attr('selected',true);\r\n");
      out.write("			\r\n");
      out.write("			// 活動\r\n");
      out.write("			let updateState = false; // false 為不可更改模式，true 為更改模式\r\n");
      out.write("			\r\n");
      out.write("			// 放棄修改\r\n");
      out.write("			$('#form').on('reset',function(){\r\n");
      out.write("				setTimeout(function(){\r\n");
      out.write("					initDatepickerValue();\r\n");
      out.write("				},1)\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 刪除活動\r\n");
      out.write("			$('#deleteBtn').on('click',function(){\r\n");
      out.write("				// deleteValue = 1 代表刪除表單，deleteValue = 0 代表編輯表單\r\n");
      out.write("				$('#deleteValue').val('1');\r\n");
      out.write("				$('#form').submit();\r\n");
      out.write("			})\r\n");
      out.write("\r\n");
      out.write("			// 確定修改(不可更改程式位置)\r\n");
      out.write("			$('#updateBtn').on('click',function(){\r\n");
      out.write("				if( updateState ){\r\n");
      out.write("					$('#form').submit();\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			// 修改活動(不可更改程式位置)\r\n");
      out.write("			$('#updateBtn').on('click',function(){\r\n");
      out.write("				if( !(updateState) ){\r\n");
      out.write("					updateState = true;\r\n");
      out.write("					$('#activityTopicId').toggleClass(\"unchangeable\").removeAttr(\"disabled\")\r\n");
      out.write("					$('#startTimeYMD').toggleClass(\"unchangeable\").removeAttr(\"disabled\")\r\n");
      out.write("					$('#startTimeH').toggleClass(\"unchangeable\").removeAttr(\"disabled\")\r\n");
      out.write("					$('#endTimeYMD').toggleClass(\"unchangeable\").removeAttr(\"disabled\")\r\n");
      out.write("					$('#endTimeH').toggleClass(\"unchangeable\").removeAttr(\"disabled\")\r\n");
      out.write("					$('#activityContentId').toggleClass(\"unchangeable\").removeAttr(\"disabled\")\r\n");
      out.write("					$('#activityType1ID').toggleClass(\"unchangeable\").removeAttr(\"disabled\")//\r\n");
      out.write("					$('#activityType2ID').toggleClass(\"unchangeable\").removeAttr(\"disabled\")//\r\n");
      out.write("					\r\n");
      out.write("					$('#deleteBtn').toggle();\r\n");
      out.write("					$('#updateBtn').text(\"確定修改\");\r\n");
      out.write("					$('#cancelBtn').toggleClass(\"unchangeable\")\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("			// 放棄修改\r\n");
      out.write("			$('#cancelBtn').on('click',function(){\r\n");
      out.write("				updateState = false;\r\n");
      out.write("				$('#activityTopicId').toggleClass(\"unchangeable\").attr(\"disabled\",\"true\")\r\n");
      out.write("				$('#startTimeYMD').toggleClass(\"unchangeable\").attr(\"disabled\",\"true\")\r\n");
      out.write("				$('#startTimeH').toggleClass(\"unchangeable\").attr(\"disabled\",\"true\")\r\n");
      out.write("				$('#endTimeYMD').toggleClass(\"unchangeable\").attr(\"disabled\",\"true\")\r\n");
      out.write("				$('#endTimeH').toggleClass(\"unchangeable\").attr(\"disabled\",\"true\")\r\n");
      out.write("				$('#activityContentId').toggleClass(\"unchangeable\").attr(\"disabled\",\"true\")\r\n");
      out.write("				$('#activityType1ID').toggleClass(\"unchangeable\").attr(\"disabled\",\"true\")//\r\n");
      out.write("				$('#activityType2ID').toggleClass(\"unchangeable\").attr(\"disabled\",\"true\")//\r\n");
      out.write("\r\n");
      out.write("				$('#deleteBtn').toggle();\r\n");
      out.write("				$('#updateBtn').text(\"修改活動\");\r\n");
      out.write("				$('#cancelBtn').toggleClass(\"unchangeable\")\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("		</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
