/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-10-25 04:47:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.HashMap;
import java.util.Map;

public final class ModifyFirstMemberVendor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-Hant-TW\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>ModifyMemberVendor</title>\r\n");
      out.write("<style>\r\n");
      out.write("fieldset { \r\n");
      out.write("        width: 500px;\r\n");
      out.write("        border: 2px solid black;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("        font-family: 標楷體;\r\n");
      out.write("        box-shadow: 0 0 20px rgba(73, 48, 48, 0.5), 0 1px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("      }\r\n");
      out.write("      legend {\r\n");
      out.write("        margin: 5px 10px;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("        padding: 0 10px 10px;\r\n");
      out.write("      }\r\n");
      out.write("      .d1 {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("      }\r\n");
      out.write("      .dd1 {\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      .dd1 div {\r\n");
      out.write("        width: 300px;\r\n");
      out.write("      }\r\n");
      out.write("      .dd2 {\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write(".spa {\r\n");
      out.write("	font-size: 10px;\r\n");
      out.write("	color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn button {\r\n");
      out.write("	margin: 20px 10px 10px 10px;\r\n");
      out.write("}\r\n");
      out.write(".deldiv{\r\n");
      out.write("	position: relative;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("    display: flex;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"d1\">\r\n");
      out.write("		<section>\r\n");
      out.write("			<form id=\"nForm\" action=\"");
      out.print(request.getContextPath() );
      out.write("/modifyMenberController\" method=\"post\">\r\n");
      out.write("			  <input type=\"hidden\" name=\"type\" value=\"form-a_mo\" />\r\n");
      out.write("			  ");

			  String userID = (String) request.getSession().getAttribute("UserID");
			  String idClass = (String) request.getSession().getAttribute("ClassMember");
			  String login = (String) request.getSession().getAttribute("Longin");
			  //String rePws = (String) request.getAttribute("Type_fg");
			  Map<String, String> userData = new HashMap<String, String>();
			  userData = (Map<String,String>)request.getAttribute("userData");
			  String bData = "";
			  String pwsString = "";// 密碼
			  String vatString = "";//統一編號
			  String vendorString = "";
			  String principalString = "";
			  String addressString = "";
		      String emailString = "";
			  
		      if(userData != null){
				  pwsString = (String) userData.get("password");
				  vatString = (String) userData.get("vat");
				  vendorString = (String) userData.get("vendor");
				  principalString = (String) userData.get("principal");
				  addressString = (String) userData.get("address");
				  emailString = (String) userData.get("email");
				  bData = (String) userData.get("bData");
			  }

			  boolean ffa = false;
				if(userID == null){
					response.sendRedirect("./LoginPage.jsp");
					return;
				}
				if(!"success".equals(bData) ){
					  if(userData != null){
						  userData.put("bData", "");
					  }
					    //request.getRequestDispatcher("/modifyMenberController").forward(request, response);
					    response.sendRedirect(request.getContextPath()+"/getMemberData");
						return;
				  }
				//是否為企業會員
				if(!idClass.equals("b") && !"fb".equals(idClass)){
					response.sendRedirect("./homePage.html");
					return;
				}
				if(!idClass.equals("b") && "fb".equals(idClass)){
					ffa = true;
				}
			  String deleteID = (String) request.getSession().getAttribute("Delete");
				if(deleteID != null){
					if(deleteID.equals("delete")){
					
      out.write("\r\n");
      out.write("					<fieldset>\r\n");
      out.write("						<legend>企業會員刪除</legend>\r\n");
      out.write("						<div class=\"dd1\">\r\n");
      out.write("							<div>\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dd1\" style=\"width: 100%;\">\r\n");
      out.write("							<div class=\"deldiv\" style=\"width: 600px;\">\r\n");
      out.write("								<input type=\"hidden\" name=\"userID\" value=\"");
      out.print(userID );
      out.write("\" />\r\n");
      out.write("								<h1 style=\"padding: 0; margin: 0; margin-right: 30px;\">是否確認刪除企業會員?</h1>\r\n");
      out.write("								\r\n");
      out.write("								<button type=\"submit\" name=\"sub\" value=\"deleteVendorCk\" >確認刪除企業會員</button>\r\n");
      out.write("								<button type=\"submit\" name=\"sub\" value=\"cancelVenCk\" style=\"margin-left: 20px;\">取消</button>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dd1\">\r\n");
      out.write("							<div>\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div>\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"btn\">\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("					");
	
					}
				}if(deleteID == null || "".equals(deleteID)) {
					 //SQLMethod sqlmethod = new SQLMethod();
						//sqlmethod.createConn();
						//ResultSet res1 = sqlmethod.searchMember(userID);
						//ResultSet res2 = sqlmethod.searchMemberDataVendor(userID);
						//String pwsString = res1.getString(2);// 密碼
						//String vatString = res1.getString(4);//統一編號
						//String vendorString = res2.getString(2);
						//String principalString = res2.getString(3);
						//String addressString = res2.getString(4);
						//String emailString = res2.getString(5);
						//sqlmethod.closeConn();
				  
      out.write("\r\n");
      out.write("					<fieldset>\r\n");
      out.write("						<legend>企業會員資料</legend>\r\n");
      out.write("							");

			              	if(ffa){
			              	
      out.write("\r\n");
      out.write("			              	<h1 style=\"color: red\">請先修改密碼</h1>\r\n");
      out.write("			              	");
	
			              	}
			              	
      out.write("\r\n");
      out.write("						<div class=\"dd1\">\r\n");
      out.write("							<div>\r\n");
      out.write("                				<label>企業名稱：");
      out.print(vendorString );
      out.write("</label>\r\n");
      out.write("              				</div>\r\n");
      out.write("              				<div>\r\n");
      out.write("              				<label>帳號：");
      out.print(userID );
      out.write("</label>\r\n");
      out.write("              				</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dd1\">\r\n");
      out.write("							<div>\r\n");
      out.write("								");
out.println("<label>密碼：**********</label>" );
	               				
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dd1\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<label>負責人：");
      out.print(principalString );
      out.write("</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<label>統一編號：");
      out.print(vatString );
      out.write("</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("              			  <div class=\"dd2\">\r\n");
      out.write("              			  	<label>住址：");
      out.print(addressString );
      out.write("</label>\r\n");
      out.write("			              </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div>\r\n");
      out.write("			              <div class=\"dd2\">\r\n");
      out.write("			              	<label>E-mail：");
      out.print(emailString );
      out.write("</label>\r\n");
      out.write("			              </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("						<div class=\"btn\">\r\n");
      out.write("							<button type=\"submit\" name=\"sub\" value=\"modifyVendor\">修改</button>\r\n");
      out.write("							<button type=\"submit\" name=\"sub\" value=\"deleteVendor\">刪除帳號</button>\r\n");
      out.write("							<button type=\"submit\" name=\"sub\" value=\"cancelVendor\">取消</button>\r\n");
      out.write("						</div>\r\n");
      out.write("				");

				}//else
				
      out.write("\r\n");
      out.write("				 \r\n");
      out.write("\r\n");
      out.write("				</fieldset>\r\n");
      out.write("			</form>\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
