/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-10-25 04:47:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Discuss;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DiscussPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/websiteForm/homeWebsiteBody1.jsp", Long.valueOf(1628063707702L));
    _jspx_dependants.put("/websiteForm/homeWebsiteHead.jsp", Long.valueOf(1627867491401L));
    _jspx_dependants.put("/websiteForm/homeWebsiteBody2.jsp", Long.valueOf(1627867491387L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("			<title>評論區</title>\r\n");
      out.write("			<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\" />\r\n");
      out.write("			");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/websiteForm/homePageTemplateCss/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/websiteForm/homePageTemplateCss/myStyle.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\" crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("		<style>\r\n");
      out.write("		body{ \r\n");
      out.write("		background-color:	#324376;\r\n");
      out.write("		}\r\n");
      out.write("			.footdiv {\r\n");
      out.write("				font-family: 'Yellowtail', cursive;\r\n");
      out.write("				/* 英文 */\r\n");
      out.write("				color: aliceblue;\r\n");
      out.write("				font-size: 10px;\r\n");
      out.write("				bottom: 0px;\r\n");
      out.write("				right: 30px;\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("			.footer {\r\n");
      out.write("				margin:  auto, auto, 10px, auto;\r\n");
      out.write("				background-color: rgb(3, 26, 102);\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("			.footer .copyRight {\r\n");
      out.write("				color: white;\r\n");
      out.write("				text-align: center;\r\n");
      out.write("				padding: 20px 0;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.div_mid {\r\n");
      out.write("				border:3px black solid;\r\n");
      out.write("				margin:50px;\r\n");
      out.write("				padding:10px;\r\n");
      out.write("				border-radius:5px;\r\n");
      out.write("				background-color:#586ba4;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.but1 {\r\n");
      out.write("				text-align:right;\r\n");
      out.write("			    border: 0;\r\n");
      out.write("			    background-color: #f5dd90;\r\n");
      out.write("			    font-family: 'Kosugi Maru', sans-serif;\r\n");
      out.write("			    /* 日文 */\r\n");
      out.write("			    border-radius: 3px\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.but1:hover {\r\n");
      out.write("			    background-color: #f76c5e;\r\n");
      out.write("			    border: 0px #003C9D solid;\r\n");
      out.write("			    font-family: 'Kosugi Maru', sans-serif;\r\n");
      out.write("			    /* 日文 */\r\n");
      out.write("			}\r\n");
      out.write("		</style>\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("		");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	// 編碼設訂
	response.setContentType("text/html;charset=UTF-8");
	request.setCharacterEncoding("UTF-8");

      out.write('	');
      out.write('\r');
      out.write('\n');

	// 取得帳號資料
	String UserID = (String)session.getAttribute("UserID");
	String ClassMember = (String)session.getAttribute("ClassMember");
	String Vat = (String)session.getAttribute("Vat");
	String Longin = (String)session.getAttribute("Longin");
	// Longin != null 為已登入狀態
	// Longin == null 為未登入狀態
	
	
	// 未登入、已登入側邊欄各項目連結不一樣
	String memberDataLink =null;
	String orderNowLink =null;
	String orderQueryLink =null;
	String commentLink =null;
	
	if(Longin == null){ // 未登入狀態
		
		memberDataLink = "'#'";
		orderNowLink = "'#'";
		orderQueryLink = "'#'";
		commentLink = "'#'";
		
	}else{ // 已登入狀態
		
		memberDataLink = "'" + request.getContextPath()  +"\\member\\ModifyFirstMember.jsp'";
		//memberDataLink = "'" + request.getContextPath()  +"\\modifyMenberController'";
		orderNowLink = "'" + request.getContextPath()  + "\\initShopCar.controller'";
		orderQueryLink = "'" + request.getContextPath()  + "\\selectAllOrderss.controller'";
		commentLink = "'"+ request.getContextPath() +"\\Discuss\\DiscussPage.jsp"+"'";		
	}
	
	
	
	//System.out.println("UserID="+UserID);
	//System.out.println("ClassMember="+ClassMember);
	//System.out.println("Vat="+Vat);
	System.out.println("Longin="+Longin);


      out.write("	\r\n");
      out.write("<nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-dark\">\r\n");
      out.write("	<!-- Navbar Brand-->\r\n");
      out.write("	<a class=\"navbar-brand ps-3 myFontTC myLetterSpace2\" href='#'>飲料線上訂</a>\r\n");
      out.write("	<!-- Sidebar Toggle-->\r\n");
      out.write("	<button class=\"myNavBtnDisappear btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0\"\r\n");
      out.write("		id=\"sidebarToggle\" href=\"#\">\r\n");
      out.write("		<i class=\"fas fa-bars\"></i>\r\n");
      out.write("	</button>\r\n");
      out.write("	<!-- Navbar Search-->\r\n");
      out.write("	<form\r\n");
      out.write("		class=\"d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0\">\r\n");
      out.write("		<div class=\"input-group\">\r\n");
      out.write("			<!-- \r\n");
      out.write("                搜尋欄\r\n");
      out.write("                <input class=\"form-control\" type=\"text\" placeholder=\"Search for...\" aria-label=\"Search for...\" aria-describedby=\"btnNavbarSearch\" />\r\n");
      out.write("                <button class=\"btn btn-primary\" id=\"btnNavbarSearch\" type=\"button\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("             -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	");

	// 登錄成功狀態
	if (Longin != null) {
	
      out.write("\r\n");
      out.write("	<div class=\"myFontTC myFontColorWhite myLetterSpace2 \">\r\n");
      out.write("		");
      out.print(UserID);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\r\n");
      out.write("		<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("			id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("			aria-expanded=\"false\"><i class=\"fas fa-user fa-fw\"></i></a>\r\n");
      out.write("			<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("				aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("				<!-- LinkTag-登出 -->\r\n");
      out.write("				<li><a class=\"dropdown-item myFontTC myTextCenter\"\r\n");
      out.write("					href=\"");
      out.print(request.getContextPath() );
      out.write("/login/LoginPage.jsp\">登出</a></li>\r\n");
      out.write("			</ul></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	// 未登錄狀態
	if (Longin == null) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- LinkTag-登入 -->\r\n");
      out.write("	<a href=\"");
      out.print(request.getContextPath() );
      out.write("/login/LoginPage.jsp\" class=\"myLoginBtn\">登入</a>\r\n");
      out.write("	<!-- LinkTag-註冊 -->\r\n");
      out.write("	<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/NewMemberAll.jsp\" class=\"mySignUpBtn\">註冊</a>\r\n");
      out.write("\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div id=\"layoutSidenav\">\r\n");
      out.write("	<div id=\"layoutSidenav_nav\">\r\n");
      out.write("		<nav class=\"sb-sidenav accordion sb-sidenav-dark\"\r\n");
      out.write("			id=\"sidenavAccordion\">\r\n");
      out.write("			<div class=\"sb-sidenav-menu\">\r\n");
      out.write("				<div class=\"nav\">\r\n");
      out.write("					<div class=\"sb-sidenav-menu-heading myLetterSpace2\">帳戶資訊</div>\r\n");
      out.write("					<!-- LinkTag-會員資料 -->\r\n");
      out.write("					<a class=\"nav-link myFontTC myLetterSpace2\"\r\n");
      out.write("						href=");
      out.print(memberDataLink);
      out.write(">\r\n");
      out.write("						<div class=\"sb-nav-link-icon\">\r\n");
      out.write("							<i class=\"fas fa-tachometer-alt\"></i>\r\n");
      out.write("						</div> 會員資料\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"sb-sidenav-menu-heading myLetterSpace2\">訂購</div>\r\n");
      out.write("					<!-- LinkTag-立即下訂 -->\r\n");
      out.write("					<a class=\"nav-link myFontTC myLetterSpace2\" href=");
      out.print(orderNowLink);
      out.write(">\r\n");
      out.write("						<div class=\"sb-nav-link-icon\">\r\n");
      out.write("							<i class=\"fas fa-tachometer-alt\"></i>\r\n");
      out.write("						</div> 立即下訂\r\n");
      out.write("					</a>\r\n");
      out.write("					<!-- LinkTag-訂單查詢 -->\r\n");
      out.write("					<a class=\"nav-link myFontTC myLetterSpace2\"\r\n");
      out.write("						href=");
      out.print(orderQueryLink);
      out.write(">\r\n");
      out.write("						<div class=\"sb-nav-link-icon\">\r\n");
      out.write("							<i class=\"fas fa-tachometer-alt\"></i>\r\n");
      out.write("						</div> 訂單查詢\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"sb-sidenav-menu-heading myLetterSpace2\">評論</div>\r\n");
      out.write("					<!-- LinkTag-我要評論 -->\r\n");
      out.write("					<a class=\"nav-link  myFontTC myLetterSpace2\" href=");
      out.print(commentLink);
      out.write(">\r\n");
      out.write("						<div class=\"sb-nav-link-icon\">\r\n");
      out.write("							<i class=\"fas fa-table\"></i>\r\n");
      out.write("						</div> 我要評論\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div id=\"layoutSidenav_content\">\r\n");
      out.write("		<main>\r\n");
      out.write("			<div class=\"container-fluid px-4\">\r\n");
      out.write("\r\n");
      out.write("		<form action=\"");
      out.print(request.getContextPath());
      out.write("/DiscussController\" method=\"get\">\r\n");
      out.write("	\r\n");
      out.write("				<div class=\"div_mid\">\r\n");
      out.write("					店家: <select name=\"shopName\">\r\n");
      out.write("						 	<option>清欣</option>\r\n");
      out.write("						 	<option>可佈可</option>\r\n");
      out.write("						 	<option>50懶</option>\r\n");
      out.write("						</select><br> <br>\r\n");
      out.write("					飲料名稱:<input type=\"text\" id=\"name\" name=\"drink\">\r\n");
      out.write("					<span id=\"idn\"></span><br><br> \r\n");
      out.write("					<input type=\"hidden\" name=\"drinkstar\" id=\"drinkstar\" value=\"\">\r\n");
      out.write("					<div id=\"stars\" class=\"left\">\r\n");
      out.write("						<img src=\"images/whitestar.png\" alt=\"\"> \r\n");
      out.write("						<img src=\"images/whitestar.png\" alt=\"\">\r\n");
      out.write("						<img src=\"images/whitestar.png\" alt=\"\"> \r\n");
      out.write("						<img src=\"images/whitestar.png\" alt=\"\"> \r\n");
      out.write("						<img src=\"images/whitestar.png\" alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"comment\" class=\"left\"></div>\r\n");
      out.write("					評論: <input type=\"text\" id=\"talk\" name=\"drinkDiscuss\"> <span id=\"ttalk\"></span><br><br>\r\n");
      out.write("					<div>\r\n");
      out.write("						<input class=\"but1\" type=\"submit\" value=\"確認\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/websiteForm/homePageTemplateJS/js/scripts.js\"></script>");
      out.write("\r\n");
      out.write("		<div class=\"footer\">\r\n");
      out.write("			<div class=\"copyRight\">&copy 2021/07/09，第三組<div class=\"footdiv animate__animated animate__bounce animate__delay-2s\">kuzi</div></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<script src=\"");
      out.print(request.getContextPath());
      out.write("/Library/jquery-3.6.0.js\"></script>\r\n");
      out.write("		<script>\r\n");
      out.write("			$(function() {\r\n");
      out.write("				$('#selectButton').on('click', function() {\r\n");
      out.write("					$('#header_select').toggleClass('show');\r\n");
      out.write("				})\r\n");
      out.write("	\r\n");
      out.write("			})\r\n");
      out.write("			// let nowTime = new Date();\r\n");
      out.write("			// console.log(\"nowTime=\"+nowTime);\r\n");
      out.write("			//制作一個星星評分\r\n");
      out.write("			var drinkstar = document.getElementById(\"drinkstar\");\r\n");
      out.write("			var divStars = document.getElementById(\"stars\");\r\n");
      out.write("			var divComment = document.getElementById(\"comment\");\r\n");
      out.write("			var attitude = [ \"較差\", \"差\", \"一般\", \"好\", \"很好\" ];\r\n");
      out.write("			var starNum = -1; //記錄當前第幾顆星星被點擊\r\n");
      out.write("			var starArray = Array.from(divStars.children); //星星陣列\r\n");
      out.write("	\r\n");
      out.write("			//滑鼠移入\r\n");
      out.write("			divStars.onmouseover = function(e) {\r\n");
      out.write("				if (e.target.tagName === \"IMG\") { //事件源是圖片\r\n");
      out.write("					//把滑鼠移動到的星星替換圖片\r\n");
      out.write("					e.target.src = \"images/blackstar.png\";\r\n");
      out.write("					//把滑鼠移動到的星星之前的星星替換圖片\r\n");
      out.write("					var prev = e.target.previousElementSibling;\r\n");
      out.write("					while (prev) {\r\n");
      out.write("						prev.src = \"images/blackstar.png\";\r\n");
      out.write("						prev = prev.previousElementSibling;\r\n");
      out.write("					}\r\n");
      out.write("					//把滑鼠移動到的星星之后的星星替換圖片\r\n");
      out.write("					var next = e.target.nextElementSibling;\r\n");
      out.write("					while (next) { //把滑鼠移動到的星星之后的星星替換圖片\r\n");
      out.write("						next.src = \"images/whitestar.png\";\r\n");
      out.write("						next = next.nextElementSibling;\r\n");
      out.write("					}\r\n");
      out.write("	\r\n");
      out.write("					var index = starArray.indexOf(e.target); //找到滑鼠移動到的星星的序號\r\n");
      out.write("					divComment.innerHTML = attitude[index]; //顯示對應的評論\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("	\r\n");
      out.write("			//滑鼠點擊\r\n");
      out.write("			divStars.onclick = function(e) {\r\n");
      out.write("				if (e.target.tagName === \"IMG\") {\r\n");
      out.write("					//記錄當前點擊的星星序號\r\n");
      out.write("					starNum = starArray.indexOf(e.target);\r\n");
      out.write("					drinkstar.value = starNum + 1;\r\n");
      out.write("					// console.log(starNum+1); 	\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("	\r\n");
      out.write("			//滑鼠移出\r\n");
      out.write("			divStars.onmouseout = function(e) {\r\n");
      out.write("				if (starNum !== -1) { //滑鼠點擊事件發生，將評分固定在點擊的星星上\r\n");
      out.write("					for (var i = 0; i < divStars.children.length; i++) {\r\n");
      out.write("						if (i <= starNum) {\r\n");
      out.write("							divStars.children[i].src = \"images/blackstar.png\";\r\n");
      out.write("	\r\n");
      out.write("						} else {\r\n");
      out.write("							divStars.children[i].src = \"images/whitestar.png\";\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("					divComment.innerHTML = attitude[starNum]; //顯示對應的評論\r\n");
      out.write("				} else {\r\n");
      out.write("					for (var i = 0; i < divStars.children.length; i++) {\r\n");
      out.write("						divStars.children[i].src = \"images/whitestar.png\";\r\n");
      out.write("					}\r\n");
      out.write("					divComment.innerHTML = \"\"; //不顯示評論\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("	</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
