/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-10-25 04:49:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.storePages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import tw.store.model.*;
import java.util.*;

public final class storeIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/websiteForm/enterpriseWebsiteBody1.jsp", Long.valueOf(1628060228972L));
    _jspx_dependants.put("/websiteForm/enterpriseWebsiteBody2.jsp", Long.valueOf(1627867491167L));
    _jspx_dependants.put("/websiteForm/enterpriseWebsiteHead.jsp", Long.valueOf(1627867491193L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("tw.store.model");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");

	response.setContentType("text/html;charset=UTF-8");
response.setHeader("Cache-Control", "no-cache"); // HTTP 1.1
response.setHeader("Pragma", "no-cache"); // HTTP 1.0
response.setDateHeader("Expires", -1); // Prevents caching at the proxy server

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"storeCss/style.css\">\r\n");
      out.write("<title>店家管理系統首頁</title>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/websiteForm/homePageTemplateCss/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/websiteForm/homePageTemplateCss/myStyle.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	// 編碼設訂
	response.setContentType("text/html;charset=UTF-8");
	request.setCharacterEncoding("UTF-8");

      out.write('	');
      out.write('\r');
      out.write('\n');

	// 取得帳號資料
	String UserID = (String)session.getAttribute("UserID");
	String ClassMember = (String)session.getAttribute("ClassMember");
	String Vat = (String)session.getAttribute("Vat");
	String Longin = (String)session.getAttribute("Longin");
	// Longin != null 為已登入狀態
	// Longin == null 為未登入狀態
	
	
	// 未登入、已登入側邊欄各項目連結不一樣
	String enterpriseDataLink =null;
	String storeManageLink =null;

	String orderQueryLink =null;
	String commentLink =null;
	String activityLink =null;
	
	if(Longin == null){ // 未登入狀態
		
		enterpriseDataLink = "'#'";
		storeManageLink = "'#'";
		activityLink ="'#'";
		
	}else{ // 已登入狀態
		
		enterpriseDataLink = "'" + request.getContextPath()  +"\\member\\ModifyFirstMemberVendor.jsp'";
		storeManageLink = "'"+ request.getContextPath() + "/checkLoginEntry.controller'"; 
		activityLink = "'"+ request.getContextPath() + "/toActivityManagePage.controller'";
	}
	
	
	
	//System.out.println("UserID="+UserID);
	//System.out.println("ClassMember="+ClassMember);
	//System.out.println("Vat="+Vat);
	System.out.println("Longin="+Longin);


      out.write("	\r\n");
      out.write("        <nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-dark\">\r\n");
      out.write("            <!-- Navbar Brand-->\r\n");
      out.write("            <a class=\"navbar-brand ps-3 myFontTC myLetterSpace2\" href=\"#\">飲料線上訂</a>\r\n");
      out.write("            <!-- Sidebar Toggle-->\r\n");
      out.write("            <button class=\"myNavBtnDisappear btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0\" id=\"sidebarToggle\" href=\"#!\"><i class=\"fas fa-bars\"></i></button>\r\n");
      out.write("            <!-- Navbar Search-->\r\n");
      out.write("            <form class=\"d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0\">\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <!-- \r\n");
      out.write("                        搜尋欄\r\n");
      out.write("                        <input class=\"form-control\" type=\"text\" placeholder=\"Search for...\" aria-label=\"Search for...\" aria-describedby=\"btnNavbarSearch\" />\r\n");
      out.write("                        <button class=\"btn btn-primary\" id=\"btnNavbarSearch\" type=\"button\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                     -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("    ");

	// 登錄成功狀態
	if (Longin != null) {
	
      out.write("\r\n");
      out.write("	<div class=\"myFontTC myFontColorWhite myLetterSpace2 \">\r\n");
      out.write("		");
      out.print(UserID);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\r\n");
      out.write("		<li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\"\r\n");
      out.write("			id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("			aria-expanded=\"false\"><i class=\"fas fa-user fa-fw\"></i></a>\r\n");
      out.write("			<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("				aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("				<!-- LinkTag-登出 -->\r\n");
      out.write("				<li><a class=\"dropdown-item myFontTC myTextCenter\"\r\n");
      out.write("					href=\"");
      out.print(request.getContextPath() );
      out.write("/login/LoginPage.jsp\">登出</a></li>\r\n");
      out.write("			</ul></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");

	// 未登錄狀態
	if (Longin == null) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- LinkTag-登入 -->\r\n");
      out.write("	<a href=\"LoginPage.jsp\" class=\"myLoginBtn\">登入</a>\r\n");
      out.write("	<!-- LinkTag-註冊 -->\r\n");
      out.write("	<a href=\"NewMemberAll.jsp\" class=\"mySignUpBtn\">註冊</a>\r\n");
      out.write("\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div id=\"layoutSidenav\">\r\n");
      out.write("            <div id=\"layoutSidenav_nav\">\r\n");
      out.write("                <nav class=\"sb-sidenav accordion sb-sidenav-dark\" id=\"sidenavAccordion\">\r\n");
      out.write("                    <div class=\"sb-sidenav-menu\">\r\n");
      out.write("                        <div class=\"nav\">\r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading myLetterSpace2\">企業</div>\r\n");
      out.write("                            <!-- LinkTag-企業資訊 -->\r\n");
      out.write("                            <a class=\"nav-link myFontTC myLetterSpace2\" href=");
      out.print(enterpriseDataLink);
      out.write(" >\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-tachometer-alt\"></i></div>\r\n");
      out.write("                                企業資訊\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"sb-sidenav-menu-heading myLetterSpace2\">店家</div>\r\n");
      out.write("                            <!--  -->\r\n");
      out.write("                            <a class=\"nav-link collapsed myFontTC myLetterSpace2\" href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\" aria-controls=\"collapseLayouts\">\r\n");
      out.write("                                <div class=\"sb-nav-link-icon\"><i class=\"fas fa-columns\"></i></div>\r\n");
      out.write("                                管理\r\n");
      out.write("                                <div class=\"sb-sidenav-collapse-arrow\"><i class=\"fas fa-angle-down\"></i></div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"collapse\" id=\"collapseLayouts\" aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\r\n");
      out.write("                                <nav class=\"sb-sidenav-menu-nested nav\">\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=");
      out.print(storeManageLink);
      out.write(" >店家管理</a>\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=\"#\">新增店家</a>\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=\"#\">查詢店家</a>\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=\"#\">修改店家</a>\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=\"#\">刪除店家</a>\r\n");
      out.write("                                    <a class=\"nav-link myFontTC myLetterSpace2\" href=");
      out.print(activityLink);
      out.write(" >店家活動</a><!-- 2021/8/4 臨時加 -->\r\n");
      out.write("                                </nav>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!--  -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"layoutSidenav_content\">\r\n");
      out.write("                <main>\r\n");
      out.write("                    <div class=\"container-fluid px-4\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');

	String userid = (String) session.getAttribute("userid");
	String company = (String) session.getAttribute("company");
	ArrayList<Store> storeList = (ArrayList<Store>) session.getAttribute("storeList");
	Store st = (Store) session.getAttribute("store");
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      tw.store.model.Store store = null;
      synchronized (session) {
        store = (tw.store.model.Store) _jspx_page_context.getAttribute("store", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (store == null){
          store = new tw.store.model.Store();
          _jspx_page_context.setAttribute("store", store, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("		<h2>店家管理系統首頁</h2>\r\n");
      out.write("		<h5>\r\n");
      out.write("			店家帳號：");
      out.print(userid);
      out.write("      企業統編：");
      out.print(company);
      out.write("\r\n");
      out.write("		</h5>\r\n");
      out.write("		<form action=\"LoginOutAction.controller\" method=\"get\">\r\n");
      out.write("			<input type=\"submit\" name=\"reLogin\" value=\"店家登出\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("<h3>店家資料</h3>\r\n");
      out.write("		<p class=\"msg\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OKmsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("		<p class=\"msg\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nulldelete}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("		<p class=\"msg\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nullupdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>帳號：");
      out.print(userid);
      out.write("</td>\r\n");
      out.write("				<td rowspan=\"4\">\r\n");
      out.write("					");

						if (st != null) {
						if (st.getPhoto() != null) {
					
      out.write(" <img src=\"");
      out.print(request.getContextPath());
      out.write("/StoreIMG/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.stuserid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width: 400px\">\r\n");
      out.write("					");

						} else {
					
      out.write(" <img src=\"storeImages/NoItem.jpg\" style=\"width: 400px\"> ");

 						}
						 } else {
					 
      out.write(" <img src=\"storeImages/NoItem.jpg\" style=\"width: 400px\"> ");

 						}
 					
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<form action=\"storeInsertEntry.controller\" method=\"post\">\r\n");
      out.write("						<input type=\"submit\" name=\"insert\" value=\"新增/查詢\">\r\n");
      out.write("					</form>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>店名：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nullmsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<form action=\"storeUpdateEntry.controller\" method=\"post\">\r\n");
      out.write("						<input type=\"submit\" name=\"delete\" value=\"修改\">\r\n");
      out.write("					</form>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>電話：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nullmsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<form action=\"storeDeleteEntry.controller\" method=\"post\">\r\n");
      out.write("						<input type=\"submit\" name=\"delete\" value=\"刪除\">\r\n");
      out.write("					</form>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("		<br />\r\n");
      out.write("		<!-- 同一企業帳號之其他分店 -->\r\n");
      out.write("		<hr />\r\n");
      out.write("		<br />\r\n");
      out.write("		<h3>其他分店資料</h3>\r\n");
      out.write("\r\n");
      out.write("		");

			for (Store sts : storeList) {

			if (sts.getStuserid().equals(userid)) {
				continue;
			} else {
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>帳號：");
      out.print(sts.getStuserid());
      out.write("</td>\r\n");
      out.write("				<td rowspan=\"4\">\r\n");
      out.write("					");

						if (sts.getPhoto() != null) {
					
      out.write(" <img src=\"");
      out.print(request.getContextPath());
      out.write("/StoreIMG/");
      out.print(sts.getStuserid());
      out.write("\" style=\"width: 400px\">\r\n");
      out.write("					");

						} else {
					
      out.write(" <img src=\"storeImages/NoItem.jpg\" style=\"width: 400px\"> ");

 	}
 
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>店名：");
      out.print(sts.getTitle());
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>電話：");
      out.print(sts.getTel());
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		");

			}
		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write(" 			</div>\r\n");
      out.write("        </main>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/websiteForm/homePageTemplateJS/js/scripts.js\"></script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
